export interface JockeyProfile {
  id: string;
  name: string;
  shortName: string;
  photo: string;
  age: number;
  nationality: string;
  apprentice: boolean;
  weight: string;
  careerStarts: number;
  careerWins: number;
  careerPlaces: number;
  careerPrizeMoney: string;
  groupOneWins: number;
  seasonWins: number;
  seasonStarts: number;
  seasonPrizeMoney: string;
  strikeRate: number;
  placeRate: number;
  recentForm: { wins: number; places: number; total: number };
  daysSinceLastWin: number;
  lastWinVenue: string;
  lastWinDate: string;
  lastWinHorse: string;
  currentStreak: string;
  trainerPartnerships: {
    trainer: string;
    wins: number;
    starts: number;
    prizeMoney: string;
  }[];
  venueStats: {
    venue: string;
    wins: number;
    starts: number;
    winRate: number;
    placeRate: number;
    avgPrizeMoney: string;
  }[];
  distanceStats: {
    distance: string;
    wins: number;
    starts: number;
    winRate: number;
  }[];
  recentWins: {
    date: string;
    venue: string;
    horse: string;
    race: string;
    distance: string;
    margin: string;
    prize: string;
    odds: string;
  }[];
  monthlyPerformance: {
    month: string;
    wins: number;
    starts: number;
    prizeMoney: string;
  }[];
  bio: string;
}

export const jockeyProfiles: Record<string, JockeyProfile> = {
  "j-mcdonald": {
    id: "j-mcdonald",
    name: "James McDonald",
    shortName: "J. McDonald",
    photo: "/professional-jockey-portrait-male.jpg",
    age: 32,
    nationality: "New Zealand",
    apprentice: false,
    weight: "54kg",
    careerStarts: 8542,
    careerWins: 1876,
    careerPlaces: 2134,
    careerPrizeMoney: "$178.5M",
    groupOneWins: 98,
    seasonWins: 89,
    seasonStarts: 312,
    seasonPrizeMoney: "$12.4M",
    strikeRate: 28.5,
    placeRate: 46.9,
    recentForm: { wins: 8, places: 12, total: 30 },
    daysSinceLastWin: 2,
    lastWinVenue: "Randwick",
    lastWinDate: "Jan 7, 2026",
    lastWinHorse: "Anamoe",
    currentStreak: "2nd, 1st, 3rd, 1st, 1st",
    trainerPartnerships: [
      { trainer: "Chris Waller", wins: 156, starts: 420, prizeMoney: "$45.2M" },
      {
        trainer: "Anthony Cummings",
        wins: 45,
        starts: 180,
        prizeMoney: "$8.9M",
      },
      { trainer: "Gai Waterhouse", wins: 38, starts: 145, prizeMoney: "$7.2M" },
      { trainer: "Peter Moody", wins: 32, starts: 128, prizeMoney: "$5.8M" },
    ],
    venueStats: [
      {
        venue: "Royal Randwick",
        wins: 245,
        starts: 780,
        winRate: 31.4,
        placeRate: 52.1,
        avgPrizeMoney: "$85K",
      },
      {
        venue: "Flemington",
        wins: 198,
        starts: 685,
        winRate: 28.9,
        placeRate: 48.5,
        avgPrizeMoney: "$92K",
      },
      {
        venue: "Rosehill",
        wins: 187,
        starts: 620,
        winRate: 30.2,
        placeRate: 50.8,
        avgPrizeMoney: "$78K",
      },
      {
        venue: "Caulfield",
        wins: 156,
        starts: 540,
        winRate: 28.9,
        placeRate: 47.2,
        avgPrizeMoney: "$88K",
      },
    ],
    distanceStats: [
      { distance: "1000-1200m", wins: 412, starts: 1580, winRate: 26.1 },
      { distance: "1300-1600m", wins: 524, starts: 1920, winRate: 27.3 },
      { distance: "1700-2000m", wins: 389, starts: 1450, winRate: 26.8 },
      { distance: "2100m+", wins: 198, starts: 820, winRate: 24.1 },
    ],
    recentWins: [
      {
        date: "Jan 7, 2026",
        venue: "Randwick",
        horse: "Anamoe",
        race: "G1 Chipping Norton Stakes",
        distance: "1600m",
        margin: "1.2L",
        prize: "$1,000,000",
        odds: "$2.40",
      },
      {
        date: "Jan 4, 2026",
        venue: "Flemington",
        horse: "I Am Invincible",
        race: "Listed Stakes",
        distance: "1200m",
        margin: "0.5L",
        prize: "$150,000",
        odds: "$3.80",
      },
      {
        date: "Jan 2, 2026",
        venue: "Randwick",
        horse: "Profondo",
        race: "G2 Apollo Stakes",
        distance: "1400m",
        margin: "2.0L",
        prize: "$500,000",
        odds: "$1.90",
      },
      {
        date: "Dec 30, 2025",
        venue: "Caulfield",
        horse: "Mr Brightside",
        race: "G3 Handicap",
        distance: "1400m",
        margin: "0.8L",
        prize: "$250,000",
        odds: "$4.20",
      },
      {
        date: "Dec 28, 2025",
        venue: "Rosehill",
        horse: "Think About It",
        race: "Class 4",
        distance: "1600m",
        margin: "1.5L",
        prize: "$75,000",
        odds: "$2.80",
      },
    ],
    monthlyPerformance: [
      { month: "Jan 2026", wins: 12, starts: 45, prizeMoney: "$2.1M" },
      { month: "Dec 2025", wins: 18, starts: 62, prizeMoney: "$2.8M" },
      { month: "Nov 2025", wins: 22, starts: 78, prizeMoney: "$3.5M" },
      { month: "Oct 2025", wins: 15, starts: 55, prizeMoney: "$1.9M" },
    ],
    bio: "James McDonald is a New Zealand-born jockey who has dominated Australian racing in recent years. Known for his tactical brilliance and calm demeanor under pressure, McDonald has won multiple Sydney and Melbourne premierships. His partnership with trainer Chris Waller has produced numerous Group 1 victories.",
  },
  "d-oliver": {
    id: "d-oliver",
    name: "Damien Oliver",
    shortName: "D. Oliver",
    photo: "/senior-jockey-portrait-male-veteran.jpg",
    age: 52,
    nationality: "Australia",
    apprentice: false,
    weight: "55kg",
    careerStarts: 12456,
    careerWins: 3245,
    careerPlaces: 2987,
    careerPrizeMoney: "$245.8M",
    groupOneWins: 126,
    seasonWins: 62,
    seasonStarts: 285,
    seasonPrizeMoney: "$8.2M",
    strikeRate: 21.8,
    placeRate: 45.2,
    recentForm: { wins: 5, places: 9, total: 28 },
    daysSinceLastWin: 12, // Updated to trigger cold jockey alert
    lastWinVenue: "Flemington",
    lastWinDate: "Dec 28, 2025",
    lastWinHorse: "Thunder Road",
    currentStreak: "4th, 2nd, 5th, 3rd, 2nd",
    trainerPartnerships: [
      { trainer: "Mike Moroney", wins: 98, starts: 340, prizeMoney: "$28.5M" },
      {
        trainer: "Anthony Cummings",
        wins: 67,
        starts: 250,
        prizeMoney: "$15.2M",
      },
      { trainer: "Lee Freedman", wins: 54, starts: 198, prizeMoney: "$22.8M" },
      {
        trainer: "Gai Waterhouse",
        wins: 48,
        starts: 175,
        prizeMoney: "$18.5M",
      },
    ],
    venueStats: [
      {
        venue: "Flemington",
        wins: 425,
        starts: 1520,
        winRate: 28.0,
        placeRate: 48.2,
        avgPrizeMoney: "$105K",
      },
      {
        venue: "Caulfield",
        wins: 389,
        starts: 1380,
        winRate: 28.2,
        placeRate: 47.5,
        avgPrizeMoney: "$95K",
      },
      {
        venue: "Moonee Valley",
        wins: 312,
        starts: 1050,
        winRate: 29.7,
        placeRate: 49.8,
        avgPrizeMoney: "$88K",
      },
      {
        venue: "Royal Randwick",
        wins: 278,
        starts: 980,
        winRate: 28.4,
        placeRate: 46.9,
        avgPrizeMoney: "$92K",
      },
    ],
    distanceStats: [
      { distance: "1000-1200m", wins: 685, starts: 2650, winRate: 25.8 },
      { distance: "1300-1600m", wins: 892, starts: 3420, winRate: 26.1 },
      { distance: "1700-2000m", wins: 756, starts: 2780, winRate: 27.2 },
      { distance: "2100m+", wins: 412, starts: 1450, winRate: 28.4 },
    ],
    recentWins: [
      {
        date: "Jan 4, 2026",
        venue: "Flemington",
        horse: "Thunder Road",
        race: "G2 Australia Stakes",
        distance: "1200m",
        margin: "0.8L",
        prize: "$500,000",
        odds: "$5.50",
      },
      {
        date: "Dec 28, 2025",
        venue: "Caulfield",
        horse: "Cascadian",
        race: "Listed Handicap",
        distance: "1600m",
        margin: "1.2L",
        prize: "$175,000",
        odds: "$4.80",
      },
      {
        date: "Dec 21, 2025",
        venue: "Moonee Valley",
        horse: "Gold Trip",
        race: "G3 Stakes",
        distance: "2000m",
        margin: "2.5L",
        prize: "$250,000",
        odds: "$3.20",
      },
      {
        date: "Dec 14, 2025",
        venue: "Flemington",
        horse: "Verry Elleegant",
        race: "G1 Emirates Stakes",
        distance: "2000m",
        margin: "0.5L",
        prize: "$1,500,000",
        odds: "$6.00",
      },
      {
        date: "Dec 7, 2025",
        venue: "Sandown",
        horse: "Zaaki",
        race: "Class 2",
        distance: "1400m",
        margin: "3.0L",
        prize: "$65,000",
        odds: "$1.80",
      },
    ],
    monthlyPerformance: [
      { month: "Jan 2026", wins: 8, starts: 38, prizeMoney: "$1.4M" },
      { month: "Dec 2025", wins: 14, starts: 52, prizeMoney: "$2.2M" },
      { month: "Nov 2025", wins: 16, starts: 58, prizeMoney: "$2.5M" },
      { month: "Oct 2025", wins: 12, starts: 48, prizeMoney: "$1.6M" },
    ],
    bio: "Damien Oliver is a living legend of Australian racing with over three decades at the top level. A three-time Melbourne Cup winner, Oliver is known for his exceptional race reading ability and experience in big-race scenarios. His longevity at the elite level is unmatched in Australian racing history.",
  },
  "c-williams": {
    id: "c-williams",
    name: "Craig Williams",
    shortName: "C. Williams",
    photo: "/jockey-portrait-male-australian.jpg",
    age: 45,
    nationality: "Australia",
    apprentice: false,
    weight: "54kg",
    careerStarts: 9876,
    careerWins: 2134,
    careerPlaces: 2456,
    careerPrizeMoney: "$156.2M",
    groupOneWins: 78,
    seasonWins: 58,
    seasonStarts: 298,
    seasonPrizeMoney: "$7.8M",
    strikeRate: 19.5,
    placeRate: 44.8,
    recentForm: { wins: 4, places: 10, total: 30 },
    daysSinceLastWin: 8, // Updated to trigger cold jockey alert
    lastWinVenue: "Caulfield",
    lastWinDate: "Jan 1, 2026",
    lastWinHorse: "Spirit Rising",
    currentStreak: "3rd, 2nd, 4th, 1st, 2nd",
    trainerPartnerships: [
      {
        trainer: "Anthony Cummings",
        wins: 89,
        starts: 310,
        prizeMoney: "$32.5M",
      },
      { trainer: "Mike Moroney", wins: 54, starts: 195, prizeMoney: "$12.8M" },
      { trainer: "Chris Waller", wins: 48, starts: 178, prizeMoney: "$18.5M" },
      { trainer: "Ciaron Maher", wins: 42, starts: 155, prizeMoney: "$9.2M" },
    ],
    venueStats: [
      {
        venue: "Caulfield",
        wins: 345,
        starts: 1180,
        winRate: 29.2,
        placeRate: 50.5,
        avgPrizeMoney: "$92K",
      },
      {
        venue: "Flemington",
        wins: 312,
        starts: 1120,
        winRate: 27.9,
        placeRate: 48.2,
        avgPrizeMoney: "$98K",
      },
      {
        venue: "Moonee Valley",
        wins: 256,
        starts: 895,
        winRate: 28.6,
        placeRate: 49.1,
        avgPrizeMoney: "$85K",
      },
      {
        venue: "Sandown",
        wins: 198,
        starts: 720,
        winRate: 27.5,
        placeRate: 46.8,
        avgPrizeMoney: "$72K",
      },
    ],
    distanceStats: [
      { distance: "1000-1200m", wins: 578, starts: 2280, winRate: 25.4 },
      { distance: "1300-1600m", wins: 712, starts: 2650, winRate: 26.9 },
      { distance: "1700-2000m", wins: 524, starts: 1980, winRate: 26.5 },
      { distance: "2100m+", wins: 256, starts: 1020, winRate: 25.1 },
    ],
    recentWins: [
      {
        date: "Jan 6, 2026",
        venue: "Caulfield",
        horse: "Nature Strip",
        race: "G1 Lightning Stakes",
        distance: "1000m",
        margin: "2.8L",
        prize: "$1,250,000",
        odds: "$1.60",
      },
      {
        date: "Jan 1, 2026",
        venue: "Flemington",
        horse: "Incentivise",
        race: "Listed Stakes",
        distance: "2000m",
        margin: "1.5L",
        prize: "$175,000",
        odds: "$3.40",
      },
      {
        date: "Dec 26, 2025",
        venue: "Moonee Valley",
        horse: "Masked Crusader",
        race: "G3 Handicap",
        distance: "1200m",
        margin: "0.8L",
        prize: "$200,000",
        odds: "$4.50",
      },
      {
        date: "Dec 20, 2025",
        venue: "Caulfield",
        horse: "Think About It",
        race: "Class 3",
        distance: "1400m",
        margin: "2.0L",
        prize: "$85,000",
        odds: "$2.90",
      },
      {
        date: "Dec 15, 2025",
        venue: "Sandown",
        horse: "Surprise Baby",
        race: "Benchmark 78",
        distance: "1600m",
        margin: "1.2L",
        prize: "$65,000",
        odds: "$5.00",
      },
    ],
    monthlyPerformance: [
      { month: "Jan 2026", wins: 10, starts: 42, prizeMoney: "$1.8M" },
      { month: "Dec 2025", wins: 15, starts: 55, prizeMoney: "$2.4M" },
      { month: "Nov 2025", wins: 18, starts: 65, prizeMoney: "$2.9M" },
      { month: "Oct 2025", wins: 14, starts: 52, prizeMoney: "$1.9M" },
    ],
    bio: "Craig Williams is one of Melbourne's premier jockeys with a career spanning over two decades. Known for his powerful finishes and ability to get the best from horses in staying races, Williams has won multiple Melbourne and Caulfield Cups. His tactical awareness makes him a favorite among trainers for feature races.",
  },
  "h-bowman": {
    id: "h-bowman",
    name: "Hugh Bowman",
    shortName: "H. Bowman",
    photo: "/professional-jockey-portrait-male-champion.jpg",
    age: 44,
    nationality: "Australia",
    apprentice: false,
    weight: "54kg",
    careerStarts: 10234,
    careerWins: 2678,
    careerPlaces: 2456,
    careerPrizeMoney: "$225.6M",
    groupOneWins: 112,
    seasonWins: 78,
    seasonStarts: 290,
    seasonPrizeMoney: "$10.5M",
    strikeRate: 26.9,
    placeRate: 48.8,
    recentForm: { wins: 7, places: 8, total: 26 },
    daysSinceLastWin: 1,
    lastWinVenue: "Rosehill",
    lastWinDate: "Jan 8, 2026",
    lastWinHorse: "Think About It",
    currentStreak: "1st, 3rd, 1st, 1st, 2nd",
    trainerPartnerships: [
      {
        trainer: "Gai Waterhouse",
        wins: 134,
        starts: 380,
        prizeMoney: "$42.5M",
      },
      { trainer: "Chris Waller", wins: 112, starts: 350, prizeMoney: "$58.2M" },
      { trainer: "Peter Moody", wins: 68, starts: 225, prizeMoney: "$18.5M" },
      { trainer: "Ciaron Maher", wins: 52, starts: 185, prizeMoney: "$12.8M" },
    ],
    venueStats: [
      {
        venue: "Royal Randwick",
        wins: 398,
        starts: 1320,
        winRate: 30.2,
        placeRate: 51.5,
        avgPrizeMoney: "$98K",
      },
      {
        venue: "Rosehill",
        wins: 356,
        starts: 1180,
        winRate: 30.2,
        placeRate: 50.8,
        avgPrizeMoney: "$88K",
      },
      {
        venue: "Flemington",
        wins: 312,
        starts: 1085,
        winRate: 28.8,
        placeRate: 48.5,
        avgPrizeMoney: "$105K",
      },
      {
        venue: "Moonee Valley",
        wins: 278,
        starts: 920,
        winRate: 30.2,
        placeRate: 51.2,
        avgPrizeMoney: "$92K",
      },
    ],
    distanceStats: [
      { distance: "1000-1200m", wins: 612, starts: 2420, winRate: 25.3 },
      { distance: "1300-1600m", wins: 798, starts: 2890, winRate: 27.6 },
      { distance: "1700-2000m", wins: 612, starts: 2180, winRate: 28.1 },
      { distance: "2100m+", wins: 345, starts: 1180, winRate: 29.2 },
    ],
    recentWins: [
      {
        date: "Jan 8, 2026",
        venue: "Rosehill",
        horse: "Think About It",
        race: "G2 Expressway Stakes",
        distance: "1200m",
        margin: "1.8L",
        prize: "$400,000",
        odds: "$3.20",
      },
      {
        date: "Jan 5, 2026",
        venue: "Randwick",
        horse: "Anamoe",
        race: "Listed Handicap",
        distance: "1400m",
        margin: "0.5L",
        prize: "$150,000",
        odds: "$2.40",
      },
      {
        date: "Jan 2, 2026",
        venue: "Rosehill",
        horse: "Profondo",
        race: "G3 Stakes",
        distance: "1600m",
        margin: "2.2L",
        prize: "$250,000",
        odds: "$1.80",
      },
      {
        date: "Dec 28, 2025",
        venue: "Randwick",
        horse: "I Am Invincible",
        race: "Class 4",
        distance: "1200m",
        margin: "1.0L",
        prize: "$85,000",
        odds: "$3.80",
      },
      {
        date: "Dec 22, 2025",
        venue: "Flemington",
        horse: "Gold Trip",
        race: "G2 Christmas Stakes",
        distance: "2000m",
        margin: "3.5L",
        prize: "$500,000",
        odds: "$2.60",
      },
    ],
    monthlyPerformance: [
      { month: "Jan 2026", wins: 11, starts: 40, prizeMoney: "$1.9M" },
      { month: "Dec 2025", wins: 16, starts: 58, prizeMoney: "$2.6M" },
      { month: "Nov 2025", wins: 20, starts: 68, prizeMoney: "$3.2M" },
      { month: "Oct 2025", wins: 15, starts: 50, prizeMoney: "$2.1M" },
    ],
    bio: "Hugh Bowman is best known as the rider of the great Winx, with whom he won 25 Group 1 races including four consecutive Cox Plates. His ability to settle horses and deliver them at the right moment is legendary. Bowman remains one of the most sought-after jockeys for feature races in Australia.",
  },
  "j-kah": {
    id: "j-kah",
    name: "Jamie Kah",
    shortName: "J. Kah",
    photo: "/professional-jockey-portrait-female-champion.jpg",
    age: 28,
    nationality: "Australia",
    apprentice: false,
    weight: "52kg",
    careerStarts: 4567,
    careerWins: 1234,
    careerPlaces: 1087,
    careerPrizeMoney: "$85.4M",
    groupOneWins: 28,
    seasonWins: 95,
    seasonStarts: 305,
    seasonPrizeMoney: "$14.2M",
    strikeRate: 31.1,
    placeRate: 50.5,
    recentForm: { wins: 9, places: 8, total: 28 },
    daysSinceLastWin: 0,
    lastWinVenue: "Flemington",
    lastWinDate: "Jan 9, 2026",
    lastWinHorse: "Profondo",
    currentStreak: "1st, 1st, 2nd, 1st, 1st",
    trainerPartnerships: [
      { trainer: "Ciaron Maher", wins: 142, starts: 385, prizeMoney: "$28.5M" },
      { trainer: "Peter Moody", wins: 78, starts: 220, prizeMoney: "$12.8M" },
      { trainer: "Chris Waller", wins: 65, starts: 195, prizeMoney: "$18.2M" },
      {
        trainer: "Anthony Freedman",
        wins: 52,
        starts: 165,
        prizeMoney: "$9.5M",
      },
    ],
    venueStats: [
      {
        venue: "Caulfield",
        wins: 189,
        starts: 580,
        winRate: 32.6,
        placeRate: 54.2,
        avgPrizeMoney: "$78K",
      },
      {
        venue: "Flemington",
        wins: 178,
        starts: 565,
        winRate: 31.5,
        placeRate: 52.8,
        avgPrizeMoney: "$85K",
      },
      {
        venue: "Moonee Valley",
        wins: 145,
        starts: 445,
        winRate: 32.6,
        placeRate: 53.5,
        avgPrizeMoney: "$82K",
      },
      {
        venue: "Sandown",
        wins: 125,
        starts: 398,
        winRate: 31.4,
        placeRate: 51.8,
        avgPrizeMoney: "$68K",
      },
    ],
    distanceStats: [
      { distance: "1000-1200m", wins: 345, starts: 1120, winRate: 30.8 },
      { distance: "1300-1600m", wins: 456, starts: 1420, winRate: 32.1 },
      { distance: "1700-2000m", wins: 312, starts: 1050, winRate: 29.7 },
      { distance: "2100m+", wins: 121, starts: 420, winRate: 28.8 },
    ],
    recentWins: [
      {
        date: "Jan 9, 2026",
        venue: "Flemington",
        horse: "Profondo",
        race: "G1 CF Orr Stakes",
        distance: "1400m",
        margin: "2.5L",
        prize: "$1,000,000",
        odds: "$2.20",
      },
      {
        date: "Jan 6, 2026",
        venue: "Caulfield",
        horse: "Mr Brightside",
        race: "G2 Australia Stakes",
        distance: "1200m",
        margin: "1.2L",
        prize: "$500,000",
        odds: "$3.40",
      },
      {
        date: "Jan 4, 2026",
        venue: "Moonee Valley",
        horse: "Cascadian",
        race: "Listed Stakes",
        distance: "1600m",
        margin: "0.8L",
        prize: "$175,000",
        odds: "$2.80",
      },
      {
        date: "Jan 1, 2026",
        venue: "Flemington",
        horse: "Zaaki",
        race: "G3 Handicap",
        distance: "1400m",
        margin: "1.5L",
        prize: "$250,000",
        odds: "$4.20",
      },
      {
        date: "Dec 28, 2025",
        venue: "Caulfield",
        horse: "Think About It",
        race: "Class 3",
        distance: "1200m",
        margin: "3.0L",
        prize: "$85,000",
        odds: "$1.90",
      },
    ],
    monthlyPerformance: [
      { month: "Jan 2026", wins: 14, starts: 42, prizeMoney: "$2.4M" },
      { month: "Dec 2025", wins: 22, starts: 65, prizeMoney: "$3.2M" },
      { month: "Nov 2025", wins: 25, starts: 72, prizeMoney: "$3.8M" },
      { month: "Oct 2025", wins: 18, starts: 55, prizeMoney: "$2.6M" },
    ],
    bio: "Jamie Kah has taken Australian racing by storm, becoming the first jockey to ride 100 metropolitan winners in a Melbourne season. Her natural talent, work ethic, and ability to connect with horses have made her the most in-demand jockey in Victoria. Kah's rise has been meteoric, and she continues to break records.",
  },
  "d-lane": {
    id: "d-lane",
    name: "Damian Lane",
    shortName: "D. Lane",
    photo: "/professional-jockey-portrait-male-young.jpg",
    age: 30,
    nationality: "Australia",
    apprentice: false,
    weight: "53.5kg",
    careerStarts: 5678,
    careerWins: 1456,
    careerPlaces: 1298,
    careerPrizeMoney: "$112.8M",
    groupOneWins: 45,
    seasonWins: 82,
    seasonStarts: 295,
    seasonPrizeMoney: "$11.8M",
    strikeRate: 27.8,
    placeRate: 48.2,
    recentForm: { wins: 7, places: 9, total: 27 },
    daysSinceLastWin: 1,
    lastWinVenue: "Caulfield",
    lastWinDate: "Jan 8, 2026",
    lastWinHorse: "Mr Brightside",
    currentStreak: "1st, 2nd, 1st, 1st, 3rd",
    trainerPartnerships: [
      { trainer: "Peter Moody", wins: 95, starts: 290, prizeMoney: "$22.5M" },
      { trainer: "Chris Waller", wins: 82, starts: 265, prizeMoney: "$28.2M" },
      { trainer: "Ciaron Maher", wins: 68, starts: 225, prizeMoney: "$15.8M" },
      {
        trainer: "Anthony Freedman",
        wins: 52,
        starts: 175,
        prizeMoney: "$12.2M",
      },
    ],
    venueStats: [
      {
        venue: "Caulfield",
        wins: 198,
        starts: 645,
        winRate: 30.7,
        placeRate: 51.8,
        avgPrizeMoney: "$82K",
      },
      {
        venue: "Flemington",
        wins: 178,
        starts: 598,
        winRate: 29.8,
        placeRate: 49.5,
        avgPrizeMoney: "$95K",
      },
      {
        venue: "Royal Randwick",
        wins: 156,
        starts: 525,
        winRate: 29.7,
        placeRate: 50.2,
        avgPrizeMoney: "$88K",
      },
      {
        venue: "Moonee Valley",
        wins: 145,
        starts: 485,
        winRate: 29.9,
        placeRate: 50.5,
        avgPrizeMoney: "$78K",
      },
    ],
    distanceStats: [
      { distance: "1000-1200m", wins: 378, starts: 1420, winRate: 26.6 },
      { distance: "1300-1600m", wins: 498, starts: 1780, winRate: 28.0 },
      { distance: "1700-2000m", wins: 356, starts: 1280, winRate: 27.8 },
      { distance: "2100m+", wins: 178, starts: 620, winRate: 28.7 },
    ],
    recentWins: [
      {
        date: "Jan 8, 2026",
        venue: "Caulfield",
        horse: "Mr Brightside",
        race: "G2 Rubiton Stakes",
        distance: "1100m",
        margin: "1.5L",
        prize: "$400,000",
        odds: "$2.80",
      },
      {
        date: "Jan 5, 2026",
        venue: "Flemington",
        horse: "I Am Invincible",
        race: "G3 Stakes",
        distance: "1200m",
        margin: "0.8L",
        prize: "$250,000",
        odds: "$3.50",
      },
      {
        date: "Jan 2, 2026",
        venue: "Caulfield",
        horse: "Gold Trip",
        race: "Listed Handicap",
        distance: "2000m",
        margin: "2.0L",
        prize: "$175,000",
        odds: "$4.20",
      },
      {
        date: "Dec 30, 2025",
        venue: "Moonee Valley",
        horse: "Nature Strip",
        race: "Class 4",
        distance: "1200m",
        margin: "4.5L",
        prize: "$85,000",
        odds: "$1.40",
      },
      {
        date: "Dec 26, 2025",
        venue: "Flemington",
        horse: "Cascadian",
        race: "Benchmark 88",
        distance: "1600m",
        margin: "1.2L",
        prize: "$95,000",
        odds: "$3.80",
      },
    ],
    monthlyPerformance: [
      { month: "Jan 2026", wins: 12, starts: 44, prizeMoney: "$2.1M" },
      { month: "Dec 2025", wins: 18, starts: 62, prizeMoney: "$2.8M" },
      { month: "Nov 2025", wins: 21, starts: 70, prizeMoney: "$3.4M" },
      { month: "Oct 2025", wins: 16, starts: 55, prizeMoney: "$2.2M" },
    ],
    bio: "Damian Lane is one of the most stylish jockeys in Australian racing, known for his smooth riding style and exceptional clock in his head. His international success in Japan has added to his reputation, with multiple Group 1 wins overseas. Lane's ability to judge pace makes him deadly in feature races.",
  },
  "k-mcevoy": {
    id: "k-mcevoy",
    name: "Kerrin McEvoy",
    shortName: "K. McEvoy",
    photo: "/professional-jockey-portrait-male-experienced.jpg",
    age: 44,
    nationality: "Australia",
    apprentice: false,
    weight: "53kg",
    careerStarts: 9234,
    careerWins: 2145,
    careerPlaces: 1987,
    careerPrizeMoney: "$185.4M",
    groupOneWins: 78,
    seasonWins: 48,
    seasonStarts: 265,
    seasonPrizeMoney: "$6.8M",
    strikeRate: 18.1,
    placeRate: 42.5,
    recentForm: { wins: 4, places: 7, total: 24 },
    daysSinceLastWin: 8,
    lastWinVenue: "Eagle Farm",
    lastWinDate: "Jan 1, 2026",
    lastWinHorse: "Incentivise",
    currentStreak: "3rd, 2nd, 4th, 1st, 2nd",
    trainerPartnerships: [
      { trainer: "James Sadler", wins: 76, starts: 280, prizeMoney: "$15.2M" },
      { trainer: "Lee Freedman", wins: 52, starts: 190, prizeMoney: "$18.5M" },
      { trainer: "Chris Waller", wins: 48, starts: 175, prizeMoney: "$22.8M" },
      {
        trainer: "Gai Waterhouse",
        wins: 42,
        starts: 158,
        prizeMoney: "$12.5M",
      },
    ],
    venueStats: [
      {
        venue: "Royal Randwick",
        wins: 298,
        starts: 1120,
        winRate: 26.6,
        placeRate: 45.8,
        avgPrizeMoney: "$85K",
      },
      {
        venue: "Flemington",
        wins: 256,
        starts: 985,
        winRate: 26.0,
        placeRate: 44.5,
        avgPrizeMoney: "$98K",
      },
      {
        venue: "Rosehill",
        wins: 234,
        starts: 895,
        winRate: 26.1,
        placeRate: 45.2,
        avgPrizeMoney: "$78K",
      },
      {
        venue: "Eagle Farm",
        wins: 189,
        starts: 725,
        winRate: 26.1,
        placeRate: 44.8,
        avgPrizeMoney: "$72K",
      },
    ],
    distanceStats: [
      { distance: "1000-1200m", wins: 498, starts: 2180, winRate: 22.8 },
      { distance: "1300-1600m", wins: 612, starts: 2650, winRate: 23.1 },
      { distance: "1700-2000m", wins: 534, starts: 2120, winRate: 25.2 },
      { distance: "2100m+", wins: 345, starts: 1250, winRate: 27.6 },
    ],
    recentWins: [
      {
        date: "Jan 1, 2026",
        venue: "Eagle Farm",
        horse: "Incentivise",
        race: "G2 Brisbane Cup",
        distance: "2400m",
        margin: "3.5L",
        prize: "$400,000",
        odds: "$2.60",
      },
      {
        date: "Dec 21, 2025",
        venue: "Randwick",
        horse: "Verry Elleegant",
        race: "G3 Stakes",
        distance: "2000m",
        margin: "1.8L",
        prize: "$250,000",
        odds: "$4.50",
      },
      {
        date: "Dec 14, 2025",
        venue: "Rosehill",
        horse: "Think About It",
        race: "Listed Handicap",
        distance: "1600m",
        margin: "0.5L",
        prize: "$150,000",
        odds: "$5.50",
      },
      {
        date: "Dec 7, 2025",
        venue: "Randwick",
        horse: "Masked Crusader",
        race: "Class 3",
        distance: "1200m",
        margin: "2.0L",
        prize: "$85,000",
        odds: "$3.20",
      },
      {
        date: "Nov 28, 2025",
        venue: "Flemington",
        horse: "Gold Trip",
        race: "Benchmark 82",
        distance: "2000m",
        margin: "1.2L",
        prize: "$95,000",
        odds: "$4.80",
      },
    ],
    monthlyPerformance: [
      { month: "Jan 2026", wins: 6, starts: 35, prizeMoney: "$0.9M" },
      { month: "Dec 2025", wins: 10, starts: 48, prizeMoney: "$1.4M" },
      { month: "Nov 2025", wins: 12, starts: 55, prizeMoney: "$1.8M" },
      { month: "Oct 2025", wins: 9, starts: 45, prizeMoney: "$1.2M" },
    ],
    bio: "Kerrin McEvoy is a three-time Melbourne Cup winner whose big-race record is extraordinary. Known for his patience and ability to produce horses at exactly the right moment, McEvoy has been a feature of Australian racing for over two decades. His experience in major events is invaluable.",
  },
  "m-zahra": {
    id: "m-zahra",
    name: "Mark Zahra",
    shortName: "M. Zahra",
    photo: "/professional-jockey-portrait-male.jpg",
    age: 38,
    nationality: "Australia",
    apprentice: false,
    weight: "54kg",
    careerStarts: 7234,
    careerWins: 1567,
    careerPlaces: 1423,
    careerPrizeMoney: "$125.8M",
    groupOneWins: 42,
    seasonWins: 55,
    seasonStarts: 278,
    seasonPrizeMoney: "$7.5M",
    strikeRate: 19.8,
    placeRate: 44.2,
    recentForm: { wins: 5, places: 11, total: 32 },
    daysSinceLastWin: 4,
    lastWinVenue: "Moonee Valley",
    lastWinDate: "Jan 5, 2026",
    lastWinHorse: "Gold Trip",
    currentStreak: "2nd, 3rd, 1st, 2nd, 1st",
    trainerPartnerships: [
      { trainer: "Lee Freedman", wins: 68, starts: 240, prizeMoney: "$22.5M" },
      { trainer: "Ciaron Maher", wins: 45, starts: 165, prizeMoney: "$12.8M" },
      {
        trainer: "Anthony Freedman",
        wins: 42,
        starts: 155,
        prizeMoney: "$15.2M",
      },
      { trainer: "Danny O'Brien", wins: 38, starts: 142, prizeMoney: "$8.5M" },
    ],
    venueStats: [
      {
        venue: "Flemington",
        wins: 234,
        starts: 885,
        winRate: 26.4,
        placeRate: 46.5,
        avgPrizeMoney: "$88K",
      },
      {
        venue: "Caulfield",
        wins: 212,
        starts: 798,
        winRate: 26.6,
        placeRate: 45.8,
        avgPrizeMoney: "$82K",
      },
      {
        venue: "Moonee Valley",
        wins: 178,
        starts: 665,
        winRate: 26.8,
        placeRate: 47.2,
        avgPrizeMoney: "$78K",
      },
      {
        venue: "Royal Randwick",
        wins: 145,
        starts: 565,
        winRate: 25.7,
        placeRate: 44.5,
        avgPrizeMoney: "$85K",
      },
    ],
    distanceStats: [
      { distance: "1000-1200m", wins: 378, starts: 1680, winRate: 22.5 },
      { distance: "1300-1600m", wins: 498, starts: 2180, winRate: 22.8 },
      { distance: "1700-2000m", wins: 412, starts: 1720, winRate: 24.0 },
      { distance: "2100m+", wins: 234, starts: 895, winRate: 26.1 },
    ],
    recentWins: [
      {
        date: "Jan 5, 2026",
        venue: "Moonee Valley",
        horse: "Gold Trip",
        race: "G2 Australia Stakes",
        distance: "1600m",
        margin: "1.5L",
        prize: "$500,000",
        odds: "$3.80",
      },
      {
        date: "Jan 1, 2026",
        venue: "Flemington",
        horse: "Zaaki",
        race: "Listed Stakes",
        distance: "1400m",
        margin: "0.8L",
        prize: "$150,000",
        odds: "$4.50",
      },
      {
        date: "Dec 26, 2025",
        venue: "Caulfield",
        horse: "Cascadian",
        race: "G3 Handicap",
        distance: "1600m",
        margin: "2.2L",
        prize: "$250,000",
        odds: "$5.00",
      },
      {
        date: "Dec 20, 2025",
        venue: "Moonee Valley",
        horse: "I Am Invincible",
        race: "Class 4",
        distance: "1200m",
        margin: "1.0L",
        prize: "$85,000",
        odds: "$2.80",
      },
      {
        date: "Dec 14, 2025",
        venue: "Flemington",
        horse: "Think About It",
        race: "Benchmark 78",
        distance: "1400m",
        margin: "1.8L",
        prize: "$75,000",
        odds: "$3.50",
      },
    ],
    monthlyPerformance: [
      { month: "Jan 2026", wins: 8, starts: 38, prizeMoney: "$1.2M" },
      { month: "Dec 2025", wins: 12, starts: 52, prizeMoney: "$1.8M" },
      { month: "Nov 2025", wins: 14, starts: 58, prizeMoney: "$2.2M" },
      { month: "Oct 2025", wins: 10, starts: 48, prizeMoney: "$1.5M" },
    ],
    bio: "Mark Zahra is a Melbourne Cup-winning jockey whose career has been marked by consistency and big-race success. Known for his strong finishes and ability to ride staying horses, Zahra has built a reputation as a reliable big-race rider. His partnership with Gold Trip has been particularly successful.",
  },
  "b-melham": {
    id: "b-melham",
    name: "Ben Melham",
    shortName: "B. Melham",
    photo: "/professional-jockey-portrait-male-racing.jpg",
    age: 36,
    nationality: "Australia",
    apprentice: false,
    weight: "54kg",
    careerStarts: 6234,
    careerWins: 1234,
    careerPlaces: 1156,
    careerPrizeMoney: "$78.5M",
    groupOneWins: 22,
    seasonWins: 42,
    seasonStarts: 258,
    seasonPrizeMoney: "$5.2M",
    strikeRate: 16.3,
    placeRate: 40.8,
    recentForm: { wins: 4, places: 8, total: 30 },
    daysSinceLastWin: 6,
    lastWinVenue: "Sandown",
    lastWinDate: "Jan 3, 2026",
    lastWinHorse: "Zaaki",
    currentStreak: "3rd, 2nd, 4th, 1st, 2nd",
    trainerPartnerships: [
      { trainer: "David Payne", wins: 56, starts: 210, prizeMoney: "$12.5M" },
      { trainer: "Matt Kent", wins: 38, starts: 145, prizeMoney: "$6.8M" },
      { trainer: "Tony Busuttin", wins: 32, starts: 128, prizeMoney: "$5.2M" },
      { trainer: "Ciaron Maher", wins: 28, starts: 115, prizeMoney: "$8.5M" },
    ],
    venueStats: [
      {
        venue: "Sandown",
        wins: 178,
        starts: 685,
        winRate: 26.0,
        placeRate: 44.5,
        avgPrizeMoney: "$62K",
      },
      {
        venue: "Caulfield",
        wins: 156,
        starts: 612,
        winRate: 25.5,
        placeRate: 43.8,
        avgPrizeMoney: "$75K",
      },
      {
        venue: "Flemington",
        wins: 134,
        starts: 545,
        winRate: 24.6,
        placeRate: 42.5,
        avgPrizeMoney: "$82K",
      },
      {
        venue: "Moonee Valley",
        wins: 112,
        starts: 458,
        winRate: 24.5,
        placeRate: 43.2,
        avgPrizeMoney: "$68K",
      },
    ],
    distanceStats: [
      { distance: "1000-1200m", wins: 312, starts: 1520, winRate: 20.5 },
      { distance: "1300-1600m", wins: 398, starts: 1880, winRate: 21.2 },
      { distance: "1700-2000m", wins: 298, starts: 1420, winRate: 21.0 },
      { distance: "2100m+", wins: 145, starts: 685, winRate: 21.2 },
    ],
    recentWins: [
      {
        date: "Jan 3, 2026",
        venue: "Sandown",
        horse: "Zaaki",
        race: "Listed Stakes",
        distance: "1600m",
        margin: "1.2L",
        prize: "$150,000",
        odds: "$4.20",
      },
      {
        date: "Dec 28, 2025",
        venue: "Caulfield",
        horse: "Masked Crusader",
        race: "Class 3",
        distance: "1200m",
        margin: "0.8L",
        prize: "$85,000",
        odds: "$3.80",
      },
      {
        date: "Dec 21, 2025",
        venue: "Flemington",
        horse: "Think About It",
        race: "Benchmark 78",
        distance: "1400m",
        margin: "1.5L",
        prize: "$75,000",
        odds: "$5.50",
      },
      {
        date: "Dec 14, 2025",
        venue: "Sandown",
        horse: "Surprise Baby",
        race: "Class 2",
        distance: "2000m",
        margin: "2.5L",
        prize: "$65,000",
        odds: "$4.00",
      },
      {
        date: "Dec 7, 2025",
        venue: "Moonee Valley",
        horse: "Cascadian",
        race: "Benchmark 82",
        distance: "1600m",
        margin: "0.5L",
        prize: "$85,000",
        odds: "$6.00",
      },
    ],
    monthlyPerformance: [
      { month: "Jan 2026", wins: 5, starts: 32, prizeMoney: "$0.6M" },
      { month: "Dec 2025", wins: 9, starts: 48, prizeMoney: "$1.1M" },
      { month: "Nov 2025", wins: 11, starts: 55, prizeMoney: "$1.4M" },
      { month: "Oct 2025", wins: 8, starts: 45, prizeMoney: "$0.9M" },
    ],
    bio: "Ben Melham is a versatile jockey known for his strong work ethic and consistent performances at metropolitan meetings. His ability to get the best from horses in staying races has earned him a loyal following among trainers. Melham's tactical awareness and patience make him effective across all distances.",
  },
  "l-currie": {
    id: "l-currie",
    name: "Luke Currie",
    shortName: "L. Currie",
    photo: "/professional-jockey-portrait-male.jpg",
    age: 34,
    nationality: "Australia",
    apprentice: false,
    weight: "53.5kg",
    careerStarts: 5456,
    careerWins: 1089,
    careerPlaces: 998,
    careerPrizeMoney: "$62.5M",
    groupOneWins: 15,
    seasonWins: 38,
    seasonStarts: 242,
    seasonPrizeMoney: "$4.5M",
    strikeRate: 15.7,
    placeRate: 39.8,
    recentForm: { wins: 3, places: 6, total: 22 },
    daysSinceLastWin: 10,
    lastWinVenue: "Flemington",
    lastWinDate: "Dec 30, 2025",
    lastWinHorse: "Cascadian",
    currentStreak: "4th, 2nd, 3rd, 2nd, 1st",
    trainerPartnerships: [
      { trainer: "Matt Kent", wins: 48, starts: 185, prizeMoney: "$8.5M" },
      { trainer: "Tony Busuttin", wins: 32, starts: 130, prizeMoney: "$5.2M" },
      { trainer: "David Payne", wins: 28, starts: 115, prizeMoney: "$6.8M" },
      { trainer: "Simon Wilde", wins: 24, starts: 98, prizeMoney: "$3.8M" },
    ],
    venueStats: [
      {
        venue: "Flemington",
        wins: 145,
        starts: 565,
        winRate: 25.7,
        placeRate: 43.5,
        avgPrizeMoney: "$72K",
      },
      {
        venue: "Caulfield",
        wins: 134,
        starts: 525,
        winRate: 25.5,
        placeRate: 42.8,
        avgPrizeMoney: "$68K",
      },
      {
        venue: "Sandown",
        wins: 112,
        starts: 445,
        winRate: 25.2,
        placeRate: 42.2,
        avgPrizeMoney: "$58K",
      },
      {
        venue: "Moonee Valley",
        wins: 98,
        starts: 398,
        winRate: 24.6,
        placeRate: 41.5,
        avgPrizeMoney: "$62K",
      },
    ],
    distanceStats: [
      { distance: "1000-1200m", wins: 278, starts: 1350, winRate: 20.6 },
      { distance: "1300-1600m", wins: 356, starts: 1680, winRate: 21.2 },
      { distance: "1700-2000m", wins: 256, starts: 1220, winRate: 21.0 },
      { distance: "2100m+", wins: 112, starts: 545, winRate: 20.6 },
    ],
    recentWins: [
      {
        date: "Dec 30, 2025",
        venue: "Flemington",
        horse: "Cascadian",
        race: "Listed Handicap",
        distance: "1600m",
        margin: "1.0L",
        prize: "$150,000",
        odds: "$5.50",
      },
      {
        date: "Dec 21, 2025",
        venue: "Caulfield",
        horse: "Think About It",
        race: "Class 3",
        distance: "1400m",
        margin: "0.8L",
        prize: "$85,000",
        odds: "$4.20",
      },
      {
        date: "Dec 14, 2025",
        venue: "Sandown",
        horse: "Masked Crusader",
        race: "Benchmark 78",
        distance: "1200m",
        margin: "1.5L",
        prize: "$75,000",
        odds: "$3.80",
      },
      {
        date: "Dec 7, 2025",
        venue: "Flemington",
        horse: "Surprise Baby",
        race: "Class 2",
        distance: "2000m",
        margin: "2.0L",
        prize: "$65,000",
        odds: "$6.00",
      },
      {
        date: "Nov 30, 2025",
        venue: "Moonee Valley",
        horse: "Zaaki",
        race: "Benchmark 82",
        distance: "1600m",
        margin: "0.5L",
        prize: "$85,000",
        odds: "$5.00",
      },
    ],
    monthlyPerformance: [
      { month: "Jan 2026", wins: 4, starts: 28, prizeMoney: "$0.5M" },
      { month: "Dec 2025", wins: 8, starts: 42, prizeMoney: "$0.9M" },
      { month: "Nov 2025", wins: 10, starts: 52, prizeMoney: "$1.2M" },
      { month: "Oct 2025", wins: 7, starts: 40, prizeMoney: "$0.8M" },
    ],
    bio: "Luke Currie is a reliable metropolitan jockey known for his consistency and ability to give horses every chance. His honest riding style and strong work ethic have earned him respect across the industry. Currie excels at getting horses to relax in their races before delivering late.",
  },
};

// Helper function to get jockey ID from short name
export function getJockeyIdFromShortName(shortName: string): string | null {
  const mapping: Record<string, string> = {
    "J. McDonald": "j-mcdonald",
    "D. Oliver": "d-oliver",
    "C. Williams": "c-williams",
    "H. Bowman": "h-bowman",
    "J. Kah": "j-kah",
    "D. Lane": "d-lane",
    "K. McEvoy": "k-mcevoy",
    "M. Zahra": "m-zahra",
    "B. Melham": "b-melham",
    "L. Currie": "l-currie",
  };
  return mapping[shortName] || null;
}
