export interface Participant {
  position: number;
  horseName: string;
  jockey: string;
  trainer: string;
  weight: string;
  barrier: number;
  form: string;
  odds: string;
  silkColor: string;
}

export interface JockeyStats {
  name: string;
  recentForm: { wins: number; places: number; total: number };
  daysSinceLastWin: number;
  lastWinVenue: string;
  lastWinDate: string;
  lastWinHorse: string;
  trainerPartnerships: { trainer: string; wins: number; starts: number }[];
  seasonWins: number;
  seasonStarts: number;
  strikeRate: number;
}

export interface Race {
  raceNumber: number;
  raceName: string;
  time: string;
  distance: string;
  prize: string;
  raceType: string;
  participants: Participant[];
}

export interface Venue {
  name: string;
  location: string;
  date: string;
  weather: string;
  trackCondition: string;
  races: Race[];
}

export interface VenueSummary {
  id: string;
  name: string;
  location: string;
  state: string;
  country: string;
  date: string;
  weather: string;
  trackCondition: string;
  raceCount: number;
  firstRaceTime: string;
  lastRaceTime: string;
  featuredRace?: string;
  imageQuery: string;
}

export const venuesList: VenueSummary[] = [
  {
    id: "flemington",
    name: "Flemington Racecourse",
    location: "Melbourne",
    state: "VIC",
    country: "Australia",
    date: "Thursday, January 9, 2026",
    weather: "Sunny, 24°C",
    trackCondition: "Good 4",
    raceCount: 9,
    firstRaceTime: "12:30 PM",
    lastRaceTime: "5:40 PM",
    featuredRace: "Group 3 Cup",
    imageQuery: "flemington racecourse melbourne horse racing",
  },
  {
    id: "randwick",
    name: "Royal Randwick",
    location: "Sydney",
    state: "NSW",
    country: "Australia",
    date: "Thursday, January 9, 2026",
    weather: "Partly Cloudy, 28°C",
    trackCondition: "Good 3",
    raceCount: 8,
    firstRaceTime: "12:45 PM",
    lastRaceTime: "5:15 PM",
    featuredRace: "Group 2 Sprint",
    imageQuery: "royal randwick racecourse sydney horse racing",
  },
  {
    id: "eagle-farm",
    name: "Eagle Farm",
    location: "Brisbane",
    state: "QLD",
    country: "Australia",
    date: "Thursday, January 9, 2026",
    weather: "Hot, 32°C",
    trackCondition: "Soft 5",
    raceCount: 7,
    firstRaceTime: "1:00 PM",
    lastRaceTime: "5:00 PM",
    featuredRace: "Listed Stakes",
    imageQuery: "eagle farm racecourse brisbane horse racing",
  },
  {
    id: "morphettville",
    name: "Morphettville",
    location: "Adelaide",
    state: "SA",
    country: "Australia",
    date: "Thursday, January 9, 2026",
    weather: "Warm, 26°C",
    trackCondition: "Good 4",
    raceCount: 8,
    firstRaceTime: "12:15 PM",
    lastRaceTime: "4:45 PM",
    imageQuery: "morphettville racecourse adelaide horse racing",
  },
  {
    id: "ascot",
    name: "Ascot Racecourse",
    location: "Perth",
    state: "WA",
    country: "Australia",
    date: "Thursday, January 9, 2026",
    weather: "Sunny, 35°C",
    trackCondition: "Good 3",
    raceCount: 9,
    firstRaceTime: "2:00 PM",
    lastRaceTime: "6:30 PM",
    featuredRace: "Group 3 Classic",
    imageQuery: "ascot racecourse perth horse racing",
  },
  {
    id: "elwick",
    name: "Elwick Racecourse",
    location: "Hobart",
    state: "TAS",
    country: "Australia",
    date: "Thursday, January 9, 2026",
    weather: "Cool, 18°C",
    trackCondition: "Soft 6",
    raceCount: 6,
    firstRaceTime: "1:30 PM",
    lastRaceTime: "4:30 PM",
    imageQuery: "elwick racecourse hobart tasmania horse racing",
  },
];

export const venueData: Venue = {
  name: "Flemington Racecourse",
  location: "Melbourne, VIC",
  date: "Thursday, January 9, 2026",
  weather: "Sunny, 24°C",
  trackCondition: "Good 4",
  races: [
    {
      raceNumber: 1,
      raceName: "Maiden Plate",
      time: "12:30 PM",
      distance: "1200m",
      prize: "$50,000",
      raceType: "Maiden",
      participants: [
        {
          position: 1,
          horseName: "Thunder Strike",
          jockey: "J. McDonald",
          trainer: "C. Waller",
          weight: "58kg",
          barrier: 3,
          form: "2-3-1",
          odds: "$3.50",
          silkColor: "bg-red-500",
        },
        {
          position: 2,
          horseName: "Midnight Sun",
          jockey: "D. Oliver",
          trainer: "M. Moroney",
          weight: "57kg",
          barrier: 7,
          form: "4-2-2",
          odds: "$4.20",
          silkColor: "bg-blue-500",
        },
        {
          position: 3,
          horseName: "Golden Dawn",
          jockey: "C. Williams",
          trainer: "A. Cummings",
          weight: "56.5kg",
          barrier: 1,
          form: "1-1-3",
          odds: "$2.80",
          silkColor: "bg-yellow-500",
        },
        {
          position: 4,
          horseName: "Storm Chaser",
          jockey: "H. Bowman",
          trainer: "G. Waterhouse",
          weight: "56kg",
          barrier: 5,
          form: "3-4-1",
          odds: "$6.00",
          silkColor: "bg-green-500",
        },
        {
          position: 5,
          horseName: "Silver Arrow",
          jockey: "K. McEvoy",
          trainer: "J. Sadler",
          weight: "55.5kg",
          barrier: 2,
          form: "2-1-4",
          odds: "$8.50",
          silkColor: "bg-gray-400",
        },
        {
          position: 6,
          horseName: "Royal Flush",
          jockey: "M. Zahra",
          trainer: "L. Freedman",
          weight: "55kg",
          barrier: 8,
          form: "5-3-2",
          odds: "$12.00",
          silkColor: "bg-purple-500",
        },
      ],
    },
    {
      raceNumber: 2,
      raceName: "Class 1 Handicap",
      time: "1:05 PM",
      distance: "1400m",
      prize: "$75,000",
      raceType: "Handicap",
      participants: [
        {
          position: 1,
          horseName: "Pacific Dream",
          jockey: "J. Kah",
          trainer: "C. Maher",
          weight: "59kg",
          barrier: 4,
          form: "1-1-2",
          odds: "$2.50",
          silkColor: "bg-teal-500",
        },
        {
          position: 2,
          horseName: "Desert Wind",
          jockey: "D. Lane",
          trainer: "P. Moody",
          weight: "58kg",
          barrier: 2,
          form: "2-1-1",
          odds: "$3.80",
          silkColor: "bg-orange-500",
        },
        {
          position: 3,
          horseName: "Mountain King",
          jockey: "B. Melham",
          trainer: "D. Payne",
          weight: "57.5kg",
          barrier: 6,
          form: "1-3-2",
          odds: "$5.50",
          silkColor: "bg-indigo-500",
        },
        {
          position: 4,
          horseName: "Ocean Breeze",
          jockey: "L. Currie",
          trainer: "M. Kent",
          weight: "56.5kg",
          barrier: 1,
          form: "3-2-1",
          odds: "$7.00",
          silkColor: "bg-cyan-500",
        },
        {
          position: 5,
          horseName: "Fire Dancer",
          jockey: "C. Newitt",
          trainer: "T. Busuttin",
          weight: "55.5kg",
          barrier: 3,
          form: "2-4-3",
          odds: "$15.00",
          silkColor: "bg-rose-500",
        },
        {
          position: 6,
          horseName: "Night Rider",
          jockey: "J. Allen",
          trainer: "L. Howley",
          weight: "55kg",
          barrier: 7,
          form: "4-2-5",
          odds: "$21.00",
          silkColor: "bg-slate-600",
        },
        {
          position: 7,
          horseName: "Swift Justice",
          jockey: "D. Yendall",
          trainer: "S. Wilde",
          weight: "54kg",
          barrier: 5,
          form: "3-3-4",
          odds: "$26.00",
          silkColor: "bg-amber-500",
        },
      ],
    },
    {
      raceNumber: 3,
      raceName: "Benchmark 78 Handicap",
      time: "1:40 PM",
      distance: "1600m",
      prize: "$100,000",
      raceType: "Benchmark",
      participants: [
        {
          position: 1,
          horseName: "Champion Spirit",
          jockey: "J. McDonald",
          trainer: "J. O'Shea",
          weight: "60kg",
          barrier: 2,
          form: "1-2-1",
          odds: "$3.00",
          silkColor: "bg-emerald-500",
        },
        {
          position: 2,
          horseName: "Victory Lane",
          jockey: "H. Bowman",
          trainer: "C. Waller",
          weight: "58.5kg",
          barrier: 5,
          form: "2-1-2",
          odds: "$3.60",
          silkColor: "bg-violet-500",
        },
        {
          position: 3,
          horseName: "Bold Warrior",
          jockey: "D. Oliver",
          trainer: "A. Cummings",
          weight: "57kg",
          barrier: 1,
          form: "1-1-3",
          odds: "$4.50",
          silkColor: "bg-red-600",
        },
        {
          position: 4,
          horseName: "Rising Star",
          jockey: "C. Williams",
          trainer: "M. Moroney",
          weight: "56kg",
          barrier: 8,
          form: "3-2-1",
          odds: "$6.50",
          silkColor: "bg-blue-600",
        },
        {
          position: 5,
          horseName: "Fast Track",
          jockey: "K. McEvoy",
          trainer: "G. Waterhouse",
          weight: "55kg",
          barrier: 4,
          form: "2-3-2",
          odds: "$9.00",
          silkColor: "bg-yellow-600",
        },
        {
          position: 6,
          horseName: "Lucky Charm",
          jockey: "M. Zahra",
          trainer: "L. Freedman",
          weight: "54.5kg",
          barrier: 6,
          form: "4-1-3",
          odds: "$11.00",
          silkColor: "bg-green-600",
        },
        {
          position: 7,
          horseName: "Steel Heart",
          jockey: "J. Kah",
          trainer: "C. Maher",
          weight: "54kg",
          barrier: 3,
          form: "2-4-2",
          odds: "$17.00",
          silkColor: "bg-gray-500",
        },
        {
          position: 8,
          horseName: "Dream Catcher",
          jockey: "D. Lane",
          trainer: "P. Moody",
          weight: "53kg",
          barrier: 7,
          form: "5-3-4",
          odds: "$31.00",
          silkColor: "bg-pink-500",
        },
      ],
    },
    {
      raceNumber: 4,
      raceName: "Listed Sprint Stakes",
      time: "2:20 PM",
      distance: "1000m",
      prize: "$150,000",
      raceType: "Listed",
      participants: [
        {
          position: 1,
          horseName: "Speed Demon",
          jockey: "D. Lane",
          trainer: "C. Waller",
          weight: "59kg",
          barrier: 1,
          form: "1-1-1",
          odds: "$1.90",
          silkColor: "bg-red-500",
        },
        {
          position: 2,
          horseName: "Lightning Bolt",
          jockey: "J. McDonald",
          trainer: "A. Cummings",
          weight: "57kg",
          barrier: 3,
          form: "2-1-2",
          odds: "$4.00",
          silkColor: "bg-yellow-400",
        },
        {
          position: 3,
          horseName: "Quick Silver",
          jockey: "H. Bowman",
          trainer: "G. Waterhouse",
          weight: "56kg",
          barrier: 6,
          form: "1-2-3",
          odds: "$6.50",
          silkColor: "bg-gray-300",
        },
        {
          position: 4,
          horseName: "Turbo Charge",
          jockey: "C. Williams",
          trainer: "M. Moroney",
          weight: "55kg",
          barrier: 2,
          form: "3-1-1",
          odds: "$8.00",
          silkColor: "bg-blue-400",
        },
        {
          position: 5,
          horseName: "Rapid Fire",
          jockey: "D. Oliver",
          trainer: "J. Sadler",
          weight: "54kg",
          barrier: 5,
          form: "2-2-4",
          odds: "$13.00",
          silkColor: "bg-orange-400",
        },
        {
          position: 6,
          horseName: "Flash Point",
          jockey: "K. McEvoy",
          trainer: "L. Freedman",
          weight: "53kg",
          barrier: 4,
          form: "4-3-2",
          odds: "$21.00",
          silkColor: "bg-purple-400",
        },
      ],
    },
    {
      raceNumber: 5,
      raceName: "Group 3 Cup",
      time: "3:00 PM",
      distance: "2000m",
      prize: "$250,000",
      raceType: "Group 3",
      participants: [
        {
          position: 1,
          horseName: "Emperor's Crown",
          jockey: "J. Kah",
          trainer: "C. Waller",
          weight: "58kg",
          barrier: 4,
          form: "1-2-1",
          odds: "$2.80",
          silkColor: "bg-amber-400",
        },
        {
          position: 2,
          horseName: "Noble Knight",
          jockey: "H. Bowman",
          trainer: "C. Maher",
          weight: "57kg",
          barrier: 2,
          form: "2-1-1",
          odds: "$3.50",
          silkColor: "bg-indigo-400",
        },
        {
          position: 3,
          horseName: "Royal Command",
          jockey: "D. Lane",
          trainer: "A. Cummings",
          weight: "56.5kg",
          barrier: 7,
          form: "1-1-2",
          odds: "$4.20",
          silkColor: "bg-rose-400",
        },
        {
          position: 4,
          horseName: "Majestic Prince",
          jockey: "J. McDonald",
          trainer: "G. Waterhouse",
          weight: "55.5kg",
          barrier: 1,
          form: "3-2-1",
          odds: "$7.00",
          silkColor: "bg-teal-400",
        },
        {
          position: 5,
          horseName: "King's Ransom",
          jockey: "C. Williams",
          trainer: "M. Moroney",
          weight: "55kg",
          barrier: 5,
          form: "2-3-2",
          odds: "$9.50",
          silkColor: "bg-cyan-400",
        },
        {
          position: 6,
          horseName: "Dynasty",
          jockey: "D. Oliver",
          trainer: "P. Moody",
          weight: "54kg",
          barrier: 3,
          form: "4-1-3",
          odds: "$14.00",
          silkColor: "bg-emerald-400",
        },
        {
          position: 7,
          horseName: "Sovereign",
          jockey: "M. Zahra",
          trainer: "L. Freedman",
          weight: "53.5kg",
          barrier: 6,
          form: "2-4-4",
          odds: "$26.00",
          silkColor: "bg-violet-400",
        },
        {
          position: 8,
          horseName: "Crown Jewel",
          jockey: "K. McEvoy",
          trainer: "J. Sadler",
          weight: "53kg",
          barrier: 8,
          form: "5-2-3",
          odds: "$41.00",
          silkColor: "bg-pink-400",
        },
      ],
    },
    {
      raceNumber: 6,
      raceName: "Class 2 Plate",
      time: "3:40 PM",
      distance: "1400m",
      prize: "$65,000",
      raceType: "Class 2",
      participants: [
        {
          position: 1,
          horseName: "Brave Heart",
          jockey: "B. Melham",
          trainer: "D. Payne",
          weight: "58kg",
          barrier: 3,
          form: "1-2-2",
          odds: "$3.20",
          silkColor: "bg-red-400",
        },
        {
          position: 2,
          horseName: "True Grit",
          jockey: "L. Currie",
          trainer: "M. Kent",
          weight: "57kg",
          barrier: 6,
          form: "2-1-3",
          odds: "$4.50",
          silkColor: "bg-blue-400",
        },
        {
          position: 3,
          horseName: "Iron Will",
          jockey: "C. Newitt",
          trainer: "T. Busuttin",
          weight: "56kg",
          barrier: 1,
          form: "1-3-1",
          odds: "$5.00",
          silkColor: "bg-gray-400",
        },
        {
          position: 4,
          horseName: "Steel Resolve",
          jockey: "J. Allen",
          trainer: "L. Howley",
          weight: "55.5kg",
          barrier: 4,
          form: "3-1-2",
          odds: "$7.50",
          silkColor: "bg-slate-400",
        },
        {
          position: 5,
          horseName: "Determined",
          jockey: "D. Yendall",
          trainer: "S. Wilde",
          weight: "55kg",
          barrier: 2,
          form: "2-2-4",
          odds: "$12.00",
          silkColor: "bg-green-400",
        },
        {
          position: 6,
          horseName: "Fearless",
          jockey: "J. Childs",
          trainer: "R. Hickmott",
          weight: "54kg",
          barrier: 5,
          form: "4-3-3",
          odds: "$18.00",
          silkColor: "bg-orange-400",
        },
      ],
    },
    {
      raceNumber: 7,
      raceName: "Benchmark 64 Handicap",
      time: "4:20 PM",
      distance: "1800m",
      prize: "$55,000",
      raceType: "Benchmark",
      participants: [
        {
          position: 1,
          horseName: "Steady Pace",
          jockey: "J. Kah",
          trainer: "C. Maher",
          weight: "60kg",
          barrier: 2,
          form: "1-1-2",
          odds: "$2.60",
          silkColor: "bg-teal-500",
        },
        {
          position: 2,
          horseName: "Marathon Man",
          jockey: "D. Lane",
          trainer: "P. Moody",
          weight: "58kg",
          barrier: 5,
          form: "2-2-1",
          odds: "$4.00",
          silkColor: "bg-purple-500",
        },
        {
          position: 3,
          horseName: "Long Distance",
          jockey: "H. Bowman",
          trainer: "C. Waller",
          weight: "57kg",
          barrier: 1,
          form: "1-2-3",
          odds: "$5.50",
          silkColor: "bg-indigo-500",
        },
        {
          position: 4,
          horseName: "Endurance",
          jockey: "J. McDonald",
          trainer: "A. Cummings",
          weight: "56kg",
          barrier: 7,
          form: "3-1-2",
          odds: "$8.00",
          silkColor: "bg-cyan-500",
        },
        {
          position: 5,
          horseName: "Stayer",
          jockey: "C. Williams",
          trainer: "G. Waterhouse",
          weight: "55kg",
          barrier: 3,
          form: "2-3-1",
          odds: "$11.00",
          silkColor: "bg-emerald-500",
        },
        {
          position: 6,
          horseName: "Distance Runner",
          jockey: "D. Oliver",
          trainer: "M. Moroney",
          weight: "54.5kg",
          barrier: 4,
          form: "4-2-2",
          odds: "$15.00",
          silkColor: "bg-rose-500",
        },
        {
          position: 7,
          horseName: "Going Strong",
          jockey: "M. Zahra",
          trainer: "L. Freedman",
          weight: "54kg",
          barrier: 6,
          form: "2-4-3",
          odds: "$26.00",
          silkColor: "bg-amber-500",
        },
      ],
    },
    {
      raceNumber: 8,
      raceName: "Open Handicap",
      time: "5:00 PM",
      distance: "1600m",
      prize: "$120,000",
      raceType: "Open",
      participants: [
        {
          position: 1,
          horseName: "Top Notch",
          jockey: "D. Lane",
          trainer: "C. Waller",
          weight: "59kg",
          barrier: 4,
          form: "1-1-1",
          odds: "$2.20",
          silkColor: "bg-yellow-500",
        },
        {
          position: 2,
          horseName: "Elite Class",
          jockey: "J. Kah",
          trainer: "C. Maher",
          weight: "57.5kg",
          barrier: 2,
          form: "2-1-2",
          odds: "$3.80",
          silkColor: "bg-blue-500",
        },
        {
          position: 3,
          horseName: "Premium Grade",
          jockey: "H. Bowman",
          trainer: "A. Cummings",
          weight: "56.5kg",
          barrier: 6,
          form: "1-2-1",
          odds: "$5.00",
          silkColor: "bg-red-500",
        },
        {
          position: 4,
          horseName: "First Rate",
          jockey: "J. McDonald",
          trainer: "G. Waterhouse",
          weight: "55.5kg",
          barrier: 1,
          form: "2-2-3",
          odds: "$8.50",
          silkColor: "bg-green-500",
        },
        {
          position: 5,
          horseName: "High Caliber",
          jockey: "C. Williams",
          trainer: "M. Moroney",
          weight: "55kg",
          barrier: 5,
          form: "3-1-2",
          odds: "$12.00",
          silkColor: "bg-purple-500",
        },
        {
          position: 6,
          horseName: "Quality Time",
          jockey: "D. Oliver",
          trainer: "P. Moody",
          weight: "54kg",
          barrier: 3,
          form: "1-3-4",
          odds: "$18.00",
          silkColor: "bg-orange-500",
        },
        {
          position: 7,
          horseName: "Upper Echelon",
          jockey: "K. McEvoy",
          trainer: "L. Freedman",
          weight: "53.5kg",
          barrier: 7,
          form: "4-2-2",
          odds: "$26.00",
          silkColor: "bg-pink-500",
        },
        {
          position: 8,
          horseName: "Superior",
          jockey: "M. Zahra",
          trainer: "J. Sadler",
          weight: "53kg",
          barrier: 8,
          form: "2-4-5",
          odds: "$41.00",
          silkColor: "bg-teal-500",
        },
      ],
    },
    {
      raceNumber: 9,
      raceName: "Closing Plate",
      time: "5:40 PM",
      distance: "1200m",
      prize: "$45,000",
      raceType: "Class 1",
      participants: [
        {
          position: 1,
          horseName: "Final Call",
          jockey: "B. Melham",
          trainer: "D. Payne",
          weight: "58kg",
          barrier: 2,
          form: "1-2-1",
          odds: "$3.00",
          silkColor: "bg-violet-500",
        },
        {
          position: 2,
          horseName: "Last Hurrah",
          jockey: "L. Currie",
          trainer: "M. Kent",
          weight: "57kg",
          barrier: 5,
          form: "2-1-2",
          odds: "$4.20",
          silkColor: "bg-rose-500",
        },
        {
          position: 3,
          horseName: "Closing Time",
          jockey: "C. Newitt",
          trainer: "T. Busuttin",
          weight: "56kg",
          barrier: 1,
          form: "1-1-3",
          odds: "$5.50",
          silkColor: "bg-amber-500",
        },
        {
          position: 4,
          horseName: "End Game",
          jockey: "J. Allen",
          trainer: "L. Howley",
          weight: "55.5kg",
          barrier: 4,
          form: "3-2-1",
          odds: "$7.00",
          silkColor: "bg-emerald-500",
        },
        {
          position: 5,
          horseName: "Sunset Run",
          jockey: "D. Yendall",
          trainer: "S. Wilde",
          weight: "55kg",
          barrier: 3,
          form: "2-3-2",
          odds: "$10.00",
          silkColor: "bg-cyan-500",
        },
        {
          position: 6,
          horseName: "Twilight Zone",
          jockey: "J. Childs",
          trainer: "R. Hickmott",
          weight: "54kg",
          barrier: 6,
          form: "4-1-4",
          odds: "$16.00",
          silkColor: "bg-indigo-500",
        },
      ],
    },
  ],
};

export const jockeyStats: Record<string, JockeyStats> = {
  "J. McDonald": {
    name: "James McDonald",
    recentForm: { wins: 8, places: 12, total: 30 },
    daysSinceLastWin: 2,
    lastWinVenue: "Randwick",
    lastWinDate: "Jan 7, 2026",
    lastWinHorse: "Anamoe",
    trainerPartnerships: [
      { trainer: "C. Waller", wins: 156, starts: 420 },
      { trainer: "A. Cummings", wins: 45, starts: 180 },
    ],
    seasonWins: 89,
    seasonStarts: 312,
    strikeRate: 28.5,
  },
  "D. Oliver": {
    name: "Damien Oliver",
    recentForm: { wins: 5, places: 9, total: 28 },
    daysSinceLastWin: 5,
    lastWinVenue: "Flemington",
    lastWinDate: "Jan 4, 2026",
    lastWinHorse: "Thunder Road",
    trainerPartnerships: [
      { trainer: "M. Moroney", wins: 98, starts: 340 },
      { trainer: "A. Cummings", wins: 67, starts: 250 },
    ],
    seasonWins: 62,
    seasonStarts: 285,
    strikeRate: 21.8,
  },
  "C. Williams": {
    name: "Craig Williams",
    recentForm: { wins: 6, places: 10, total: 25 },
    daysSinceLastWin: 3,
    lastWinVenue: "Caulfield",
    lastWinDate: "Jan 6, 2026",
    lastWinHorse: "Nature Strip",
    trainerPartnerships: [
      { trainer: "A. Cummings", wins: 89, starts: 310 },
      { trainer: "M. Moroney", wins: 54, starts: 195 },
    ],
    seasonWins: 71,
    seasonStarts: 298,
    strikeRate: 23.8,
  },
  "H. Bowman": {
    name: "Hugh Bowman",
    recentForm: { wins: 7, places: 8, total: 26 },
    daysSinceLastWin: 1,
    lastWinVenue: "Rosehill",
    lastWinDate: "Jan 8, 2026",
    lastWinHorse: "Think About It",
    trainerPartnerships: [
      { trainer: "G. Waterhouse", wins: 134, starts: 380 },
      { trainer: "C. Waller", wins: 112, starts: 350 },
    ],
    seasonWins: 78,
    seasonStarts: 290,
    strikeRate: 26.9,
  },
  "K. McEvoy": {
    name: "Kerrin McEvoy",
    recentForm: { wins: 4, places: 7, total: 24 },
    daysSinceLastWin: 8,
    lastWinVenue: "Eagle Farm",
    lastWinDate: "Jan 1, 2026",
    lastWinHorse: "Incentivise",
    trainerPartnerships: [
      { trainer: "J. Sadler", wins: 76, starts: 280 },
      { trainer: "L. Freedman", wins: 52, starts: 190 },
    ],
    seasonWins: 48,
    seasonStarts: 265,
    strikeRate: 18.1,
  },
  "M. Zahra": {
    name: "Mark Zahra",
    recentForm: { wins: 5, places: 11, total: 32 },
    daysSinceLastWin: 4,
    lastWinVenue: "Moonee Valley",
    lastWinDate: "Jan 5, 2026",
    lastWinHorse: "Gold Trip",
    trainerPartnerships: [
      { trainer: "L. Freedman", wins: 68, starts: 240 },
      { trainer: "C. Maher", wins: 45, starts: 165 },
    ],
    seasonWins: 55,
    seasonStarts: 278,
    strikeRate: 19.8,
  },
  "J. Kah": {
    name: "Jamie Kah",
    recentForm: { wins: 9, places: 8, total: 28 },
    daysSinceLastWin: 0,
    lastWinVenue: "Flemington",
    lastWinDate: "Jan 9, 2026",
    lastWinHorse: "Profondo",
    trainerPartnerships: [
      { trainer: "C. Maher", wins: 142, starts: 385 },
      { trainer: "P. Moody", wins: 78, starts: 220 },
    ],
    seasonWins: 95,
    seasonStarts: 305,
    strikeRate: 31.1,
  },
  "D. Lane": {
    name: "Damian Lane",
    recentForm: { wins: 7, places: 9, total: 27 },
    daysSinceLastWin: 1,
    lastWinVenue: "Caulfield",
    lastWinDate: "Jan 8, 2026",
    lastWinHorse: "Mr Brightside",
    trainerPartnerships: [
      { trainer: "P. Moody", wins: 95, starts: 290 },
      { trainer: "C. Waller", wins: 82, starts: 265 },
    ],
    seasonWins: 82,
    seasonStarts: 295,
    strikeRate: 27.8,
  },
  "B. Melham": {
    name: "Ben Melham",
    recentForm: { wins: 4, places: 8, total: 30 },
    daysSinceLastWin: 6,
    lastWinVenue: "Sandown",
    lastWinDate: "Jan 3, 2026",
    lastWinHorse: "Zaaki",
    trainerPartnerships: [
      { trainer: "D. Payne", wins: 56, starts: 210 },
      { trainer: "M. Kent", wins: 38, starts: 145 },
    ],
    seasonWins: 42,
    seasonStarts: 258,
    strikeRate: 16.3,
  },
  "L. Currie": {
    name: "Luke Currie",
    recentForm: { wins: 3, places: 6, total: 22 },
    daysSinceLastWin: 10,
    lastWinVenue: "Flemington",
    lastWinDate: "Dec 30, 2025",
    lastWinHorse: "Cascadian",
    trainerPartnerships: [
      { trainer: "M. Kent", wins: 48, starts: 185 },
      { trainer: "T. Busuttin", wins: 32, starts: 130 },
    ],
    seasonWins: 38,
    seasonStarts: 242,
    strikeRate: 15.7,
  },
  "C. Newitt": {
    name: "Craig Newitt",
    recentForm: { wins: 2, places: 5, total: 20 },
    daysSinceLastWin: 14,
    lastWinVenue: "Morphettville",
    lastWinDate: "Dec 26, 2025",
    lastWinHorse: "Coolangatta",
    trainerPartnerships: [
      { trainer: "T. Busuttin", wins: 42, starts: 170 },
      { trainer: "S. Wilde", wins: 28, starts: 115 },
    ],
    seasonWins: 29,
    seasonStarts: 215,
    strikeRate: 13.5,
  },
  "J. Allen": {
    name: "John Allen",
    recentForm: { wins: 3, places: 7, total: 25 },
    daysSinceLastWin: 7,
    lastWinVenue: "Ballarat",
    lastWinDate: "Jan 2, 2026",
    lastWinHorse: "Verry Elleegant",
    trainerPartnerships: [
      { trainer: "L. Howley", wins: 38, starts: 155 },
      { trainer: "D. Payne", wins: 25, starts: 105 },
    ],
    seasonWins: 35,
    seasonStarts: 230,
    strikeRate: 15.2,
  },
  "D. Yendall": {
    name: "Dean Yendall",
    recentForm: { wins: 2, places: 4, total: 18 },
    daysSinceLastWin: 12,
    lastWinVenue: "Geelong",
    lastWinDate: "Dec 28, 2025",
    lastWinHorse: "Surprise Baby",
    trainerPartnerships: [
      { trainer: "S. Wilde", wins: 35, starts: 145 },
      { trainer: "R. Hickmott", wins: 22, starts: 98 },
    ],
    seasonWins: 26,
    seasonStarts: 198,
    strikeRate: 13.1,
  },
  "J. Childs": {
    name: "Jordan Childs",
    recentForm: { wins: 4, places: 6, total: 23 },
    daysSinceLastWin: 5,
    lastWinVenue: "Pakenham",
    lastWinDate: "Jan 4, 2026",
    lastWinHorse: "Masked Crusader",
    trainerPartnerships: [
      { trainer: "R. Hickmott", wins: 45, starts: 175 },
      { trainer: "M. Kent", wins: 32, starts: 125 },
    ],
    seasonWins: 44,
    seasonStarts: 245,
    strikeRate: 18.0,
  },
};
